### ISSUE TITLE
Problem to install LXESP8266DMX libray

### ISSUE THREAD

**Issue by iz1kbp** [claudeheintz/LXESP8266DMX#12]
Hi, sorry for troubble.I'm unable to install the libray.
I've download the zip file and then install with "zip" option.
I've tried with IDE 1.8.9 release and IDE 2.3, two empty project, on wemos d1 mini.
Have you some idea about this problem,Have I lost some information for the installation procedure?

thank you again
Mario

here the ctrl-c of error in ver 1.8.9
////////////////////////////////////////-----------------------error------------------------------/////////////////////////////////

Arduino:1.8.9 (Windows 7), Scheda:"WeMos D1 R2 & mini, 80 MHz, 4M (1M SPIFFS), v2 Prebuilt (MSS=536), Disabled, None, 921600"

java.io.FileNotFoundException: C:\Users\Mario\AppData\Local\Temp\arduino_709842\LXESP8266DMX-master147796\LXESP8266DMX-master\examples\feather shield ESP8266:ESP32\FeatherDMXShieldDesign.pdf (La sintassi del nome del file, della directory o del volume non è corretta)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at processing.app.tools.ZipDeflater.deflate(ZipDeflater.java:50)
	at processing.app.Base.handleAddLibrary(Base.java:2276)
	at processing.app.Base$6.actionPerformed(Base.java:1095)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
C:\Users\Mario\AppData\Local\Temp\arduino_709842\LXESP8266DMX-master147796\LXESP8266DMX-master\examples\feather shield ESP8266:ESP32\FeatherDMXShieldDesign.pdf (La sintassi del nome del file, della directory o del volume non è corretta)

Questo report potrebbe essere più ricco di informazioni abilitando l'opzione
"Mostra un output dettagliato durante la compilazione"
in "File -> Impostazioni"

**Comment by claudeheintz** [comment]
It looks like you are trying to compile a PDF file.  Is this output from trying to include the library? 

You can unzip the library downloaded from GitHub.  Remove the "-master" from the end of the folder name( so it is "LXESP8266DMX").  Put it in the [path-to-arduino-folder]/Arduino/libraries folder.  Restart Arduino IDE.  You should be able to include the library in a sketch.

[path-to-arduino-folder]/Arduino/libraries/LXESP8266DMX

**Comment by iz1kbp** [comment]
Hi Claude,yes...this is the direct output from "import using zip". Normally,I use this procedure to import "forched" libray from GitHub.using the "..unziping, delete "master" and insert manually in library folder" is a good work around . Now all is ok.thank you again.have a nice day. Mario





 






**********************************************************Mario Brustia - IZ1KBPLOC JN45IK - 45.4167N 8.6667E - QRZ Pilota SAPR ENAC A2 ITA-RP-000000609ABA / IT-STS-012008 OPERATORE ENAC:ITEAYYIFSKOPERATORE EASA:ITA3YNC64M41Y776R2SMPix4D certified user - QSC certified userP.IVA 02638890034 - Albo Artigiani N. ***@***.***@pec.itwww.meteotrecate.it  www.aprtrecate.itFacebook >> brustiamariosent from webmail**********************************************************













Da: "Claude Heintz" ***@***.***
A: "claudeheintz/LXESP8266DMX" ***@***.***
Cc: "Mario" ***@***.***,"Author" ***@***.***
Data: Wed, 10 Apr 2024 09:17:17 -0700
Oggetto: Re: [claudeheintz/LXESP8266DMX] Problem to install LXESP8266DMX libray (Issue #12)


It looks like you are trying to compile a PDF file.  Is this output from trying to include the library?
You can unzip the library downloaded from GitHub.  Remove the "-master" from the end of the folder name( so it is "LXESP8266DMX").  Put it in the [path-to-arduino-folder]/Arduino/libraries folder.  Restart Arduino IDE.  You should be able to include the library in a sketch.
[path-to-arduino-folder]/Arduino/libraries/LXESP8266DMX
